package StoreApp;

import java.io.IOException;

/**
* StoreApp/StorePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Store.idl
* Saturday, October 24, 2020 8:41:11 PM CEST
*/

public abstract class StorePOA extends org.omg.PortableServer.Servant
 implements StoreApp.StoreOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addItem", new java.lang.Integer (0));
    _methods.put ("listItem", new java.lang.Integer (1));
    _methods.put ("removeItem", new java.lang.Integer (2));
    _methods.put ("listItemAvailability", new java.lang.Integer (3));
    _methods.put ("sellItem", new java.lang.Integer (4));
    _methods.put ("purchaseItem", new java.lang.Integer (5));
    _methods.put ("findItem", new java.lang.Integer (6));
    _methods.put ("returnItem", new java.lang.Integer (7));
    _methods.put ("exchangeItem", new java.lang.Integer (8));
    _methods.put ("shutdown", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Manager
       case 0:  // StoreApp/Store/addItem
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         String itemName = in.read_string ();
         int quantity = in.read_long ();
         double price = in.read_double ();
         this.addItem (userID, itemID, itemName, quantity, price);
         out = $rh.createReply();
         break;
       }

       case 1:  // StoreApp/Store/listItem
       {
         String userID = in.read_string ();
         String $result = null;
         $result = this.listItem (userID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // StoreApp/Store/removeItem
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         int quantity = in.read_long ();
         try {
			this.removeItem (userID, itemID, quantity);
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
         out = $rh.createReply();
         break;
       }


  // Generic
       case 3:  // StoreApp/Store/listItemAvailability
       {
         String $result = null;
         $result = this.listItemAvailability ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // StoreApp/Store/sellItem
       {
         String customerID = in.read_string ();
         String itemID = in.read_string ();
         String dateOfPurchase = in.read_string ();
         boolean $result = false;
         $result = this.sellItem (customerID, itemID, dateOfPurchase);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Customer
       case 5:  // StoreApp/Store/purchaseItem
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         String dateOfPurchase = in.read_string ();
         String $result = null;
         try {
			$result = this.purchaseItem (userID, itemID, dateOfPurchase);
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // StoreApp/Store/findItem
       {
         String userID = in.read_string ();
         String itemName = in.read_string ();
         String $result = null;
         $result = this.findItem (userID, itemName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // StoreApp/Store/returnItem
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         String dateOfReturn = in.read_string ();
         String $result = null;
         $result = this.returnItem (userID, itemID, dateOfReturn);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // StoreApp/Store/exchangeItem
       {
         String userID = in.read_string ();
         String newItemID = in.read_string ();
         String oldItemID = in.read_string ();
         String $result = null;
         $result = this.exchangeItem (userID, newItemID, oldItemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // StoreApp/Store/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:StoreApp/Store:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Store _this() 
  {
    return StoreHelper.narrow(
    super._this_object());
  }

  public Store _this(org.omg.CORBA.ORB orb) 
  {
    return StoreHelper.narrow(
    super._this_object(orb));
  }


} // class StorePOA
