package StoreApp;


/**
* StoreApp/StoreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Store.idl
* Saturday, October 24, 2020 8:41:11 PM CEST
*/

public interface StoreOperations 
{

  // Manager
  void addItem (String userID, String itemID, String itemName, int quantity, double price);
  String listItem (String userID);
  void removeItem (String userID, String itemID, int quantity);

  // Generic
  String listItemAvailability ();
  boolean sellItem (String customerID, String itemID, String dateOfPurchase);

  // Customer
  String purchaseItem (String userID, String itemID, String dateOfPurchase);
  String findItem (String userID, String itemName);
  String returnItem (String userID, String itemID, String dateOfReturn);
  String exchangeItem (String userID, String newItemID, String oldItemID);
  void shutdown ();
} // interface StoreOperations
