package StoreApp;


/**
* StoreApp/Store.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Store.idl
* Saturday, October 24, 2020 8:41:11 PM CEST
*/

public interface Store extends StoreOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Store
