module StoreApp
{
  interface Store
  {
 	// Manager
	void addItem(in string userID, in string itemID, in string itemName, in long quantity, in double price);
	string listItem(in string userID);
	void removeItem(in string userID, in string itemID, in long quantity);

	// Generic	
	string listItemAvailability();
	boolean sellItem(in string customerID, in string itemID, in string dateOfPurchase);

  // Customer
	string purchaseItem(in string userID, in string itemID, in string dateOfPurchase);
	string findItem(in string userID, in string itemName);
	string returnItem(in string userID, in string itemID, in string dateOfReturn);
	string exchangeItem(in string userID, in string newItemID, in string oldItemID);
  oneway void shutdown();
  };
};
